config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts do
  	resources :comments
  end
  resources :users

  get '/login', to: 'users#login'
  post '/login', to: 'users#login'

  post '/logout', to: 'users#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post

	validates :post_id, :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
	validates :title, :content, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :posts

	validates :name, :email, :password, presence: true
	validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include UsersHelper

	def create
		current_user
		if @current_user
			@comment = Comment.new
			@comment.content = params[:comment][:content]
			@comment.post_id = params[:post_id]
			@comment.user_id = @current_user.id
			@comment.save

			@post = Post.find_by(id: params[:post_id])
			redirect_to @post
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include UsersHelper

	def show
		@post = Post.find_by(id: params[:id])
		@comment = Comment.new
		@comment.post_id = @post.id
	end

	def index
		@posts = Post.all
	end

	def edit
		current_user

		if @current_user.id
			@post = Post.find_by(id: params[:id])
			if @current_user.id === @post.user_id
				return @post
			end
		end
	end

	def new
		current_user

		if @current_user
			@post = Post.new
		else
			redirect_to '/login'
		end
	end

	def create
		current_user

		if @current_user
			@post = Post.new

			@post.title = params[:post]['title']
			@post.content = params[:post]['content']
			@post.user_id = @current_user['id']

			@post.save

			redirect_to @post
		else
			redirect_to '/login'
		end
	end

	def update
		current_user

		puts params[:post]

		if @current_user && params && params[:id]
			@post = Post.find_by(id: params[:id])

			@post.title = params[:post][:title]
			@post.content = params[:post][:content]

			@post.save

			redirect_to @post
		else
			redirect_to '/login'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by(id: params[:id])
	end

	def new
		@user = User.new
	end

	def login
		login_get if request.get?
		login_post if request.post?
	end

	def logout
		reset_session
		redirect_to '/'
	end

	def create
		@user = User.new

		@user.name = params[:user][:name]
		@user.email = params[:user][:email]
		@user.password = params[:user][:password]
		@user.password_confirmation = params[:user][:password_confirmation]

		@user.save

		if @user.authenticate(params[:user][:password])
			session[:current_user] = {
				id: @user.id,
				name: @user.name,
				email: @user.email
			}
		end

		redirect_to @user
	end

	private
		def login_get
			@user = User.new
		end

		def login_post
			@user = User.find_by(email: params[:user][:email])

			if @user
				if @user.try(:authenticate, params[:user][:password])
					session[:current_user] = {
						id: @user.id,
						name: @user.name,
						email: @user.email
					}
				end
			end

			redirect_to '/'
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
	  	if session && session[:current_user] && session[:current_user]['id']
	  		@current_user = User.find_by(id: session[:current_user]['id'])
	  	else
	  		@current_user = false
	  	end
	end
end

app/views/comments/_form.html.erb
<% if @current_user %>
	<%= form_for [@post, @comment] do |form| %>
		<div class="field-controller">
			<%= form.label :content, "Comment" %>
			<%= form.text_area :content %>
		</div>
		<%= form.submit %>
	<% end %>
<% end %>

app/views/comments/_list.html.erb
<% @post.comments.reverse.each do |comment| 
	@commenter = User.find(comment.user_id) %>
	<div class="comment">
		<%= comment.content %>
		<div class="credits">
			<%= link_to @commenter.name, @commenter %> | <%= comment.created_at.strftime("%m/%d/%Y %I:%M%p") %>
		</div>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<% current_user %>

<navigation>
	<div class="navbar">
		<ul>
			<li><a href="/">Home</a></li>
			<% if @current_user %>
				<li><%= link_to "Logout", logout_url, method: :post %></li>
				<li class="pull-right"><%= link_to "Make a new Post", new_post_url %></li>
			<% else %>
				<li><%= link_to "Log In", login_url %></li>
				<li><%= link_to "Sign Up", new_user_url %></li>
			<% end %>
		</ul>
	</div>
</navigation>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>

	<div class="field-container">
		<%= form.label :title %>
		<%= form.text_field :title %>
	</div>
	<div class="field-container">
		<%= form.label :content %>
		<%= form.text_area :content %>
	</div>

	<%= form.submit %>

<% end %>

app/views/posts/_post.html.erb
<article>
	<div class="post">
		<h3><%= link_to @post.title, @post %></h3>
		<p><%= truncate(@post.content, length: 50) %></p>
		<div class="credits">
			Author: <%= link_to @post.user.name, @post.user %> | <%= @post.created_at.strftime("%m/%d/%Y %I:%M%p") %> | <%= pluralize(@post.comments.count, 'comment') %>
			<% if @display_edit && @current_user && @current_user.id === @post.user.id %>
				&nbsp;|&nbsp;<%= link_to "Edit Post", "/posts/#{@post.id}/edit" %>
			<% end %>
		</div>
	</div>
</article>

app/views/posts/edit.html.erb
<%= render partial: 'form', local: { post: @post } %>

app/views/posts/index.html.erb
<% current_user %>

<h1>blog</h1>

<% @posts.each do |post|
	@post = post
	@display_edit = :true %>
	<%= render 'post', locals: { post: @post, display_edit: @display_edit, current_user: @current_user } %>
<% end %>

app/views/posts/new.html.erb
<%= render partial: 'form', local: { post: @post } %>

app/views/posts/show.html.erb
<% current_user %>

<% @display_edit = :true %>

<%= render 'post', locals: { post: @post, display_edit: @display_edit, current_user: @current_user } %>

<%= render 'comments/form', locals: { post: @post, comment: @comment, current_user: @current_user } %>

<%= render 'comments/list', locals: { post: @post, comments: @comments } %>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_for User.new, url: '/login' do |form| %>
	<div class="field-container">
		<%= form.label :email %>
		<%= form.text_field :email %>
	</div>
	<div class="field-container">
		<%= form.label :password %>
		<%= form.password_field :password %>
	</div>
	<%= form.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
	<div>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</div>
	<div>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>
	<div>
		<%= form.label :password %>
		<%= form.password_field :password %>
	</div>
	<div>
		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation %>
	</div>
	<%= form.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<% if @user.posts %>
	<h3>Posts</h3>
<% end %>
<% @user.posts.each do |post|
	@post = post
	@display_edit = :true %>
	<%= render partial: '/posts/post', locals: { post: @post, display_edit: @display_edit, current_user: @current_user } %>
<% end %>